# Generated by Django 3.1.7 on 2021-03-30 17:18

from django.db import migrations
from django.contrib.auth.models import User

from src.utils.config import Config


def create_user(apps, schema_editor):
    config = Config()
    User.objects.create_superuser(
        username=config.superuser.username,
        email=config.superuser.email,
        password=config.superuser.password,
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_user)
    ]
