database:
  ENGINE: django.db.backends.postgresql
  NAME: postgres
  USER: postgres
  PASSWORD: changeme
  HOST: 127.0.0.1
  PORT: 5432

superuser:
  username: test
  email: test@test.com
  password: test

cors:
  whitelist:
    - http://localhost:8080
    - http://127.0.0.1:8080
