# Generated by Django 3.1.7 on 2021-05-06 12:59

import json
from django.db import migrations

from src.apps.settings.models import Topic

def load_topics(apps, schema_editor):
    with open('resources/embeddings.json') as f:
        data = json.load(f)

        for key, val in data.items():
            topic = Topic(name=key, embedding=val)
            topic.save()


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_topics),
    ]
